# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
 branches:
   include:
     - master

pr:
 branches:
   include:
     - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  displayName: Prepare SonarCloud
  inputs:
    projectName: 'SSDT Lifecycle Extension'
    projectKey: 'SSDTLifecycleExtension'
    projectVersion: '$(Build.BuildId)'
    organization: 'herdo-github'
    SonarCloud: 'SonarCloud-CodeAnalysis-Server'

- task: NuGetToolInstaller@0
  displayName: NuGet Tool Installer

- task: NuGetCommand@2
  displayName: Restore NuGet packages
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: Run tests
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: true

- task: SonarCloudAnalyze@1 
  displayName: Run SonarCloud Analyzer

- task: PowerShell@2
  name: SignVSIX
  displayName: Sign VSIX
  inputs:
    targetType: filePath
    filePath: |
     '$(Build.SourcesDirectory)\build\sign-vsix.ps1'

- task: CopyFiles@2
  name: CopyDeploymentData
  displayName: Copy deployment data to artifact staging directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     deployment\*
     README.md
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  name: CopyVSIX
  displayName: Copy VSIX to artifact staging directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **\bin\Release\*.vsix
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publish VSIX build artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: VSIX